mariadb:
  image: mariadb
  container_name: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
    - 3306:3306

app:
  image: ruby
  container_name: app
  volumes:
    - ../cool:/var/app
  links:
    - mariadb
  environment:
    RACK_ENV: development
  working_dir: 
    /var/app

nginx:
  image: nginx
  container_name: nginx
  volumes:
    - ./nginx/config:/etc/nginx
  links:
    - app
  ports:
    - 80:80
    - 443:443
